name: sync
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
env:
  IMDB_COOKIEATMAIN: ${{ secrets.IMDB_COOKIEATMAIN }}
  IMDB_COOKIEUBIDMAIN: ${{ secrets.IMDB_COOKIEUBIDMAIN }}
  IMDB_LISTS: ${{ secrets.IMDB_LISTS }}
  TRAKT_EMAIL: ${{ secrets.TRAKT_EMAIL }}
  TRAKT_PASSWORD: ${{ secrets.TRAKT_PASSWORD }}
  TRAKT_CLIENTID: ${{ secrets.TRAKT_CLIENTID }}
  TRAKT_CLIENTSECRET: ${{ secrets.TRAKT_CLIENTSECRET }}
  SYNC_SKIPHISTORY: ${{ secrets.SYNC_SKIPHISTORY }}
  SYNC_MODE: ${{ secrets.SYNC_MODE }}
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Build
        run: make build
      - name: Sync
        run: make sync
